#!/bin/bash

export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

############################################################
#
#       1.位置参量
#
############################################################
ARGUMENT1="$1"

set -eu
#set -x

echo_color()
{
        echo -e "\e[1m\e[40;$2m$1\e[0m"
}

echo_error()
{
        echo_color "$1" "31"
        exit 1
}

echo_warning()
{
        echo_color "$1" "33"
        sleep 5
}

if [[ "$(id -u)" != "0" ]]; then
        echo_error "Error: must run with root"
fi

if [[ -s "/usr/local/bin/myfunction.sh" ]]; then
        . /usr/local/bin/myfunction.sh
else
        echo_error "Error: myfunction.sh not found"
fi

############################################################
#
#       2.全局变量
#
############################################################
BACKUP_ROOT="/backup"

############################################################
#
#       3.初始化
#
############################################################
# 创建目录
mkdir -p ${BACKUP_ROOT}/log

# 同步时间
adjust_time
hwclock -w

# 检测指令
if ( ! type -p mysql &> /dev/null ); then
        echo_error "Error: mysql not found"
fi

############################################################
#
#       4.次要函数
#
############################################################

############################################################
#
#       5.主要函数
#
############################################################
default()
{
        echo "backup-policy: unrecognized option '$1'"
        
        echo "Usage: backup-policy [timer|init]"
        echo ""
        
        exit 1
}

init()
{
        # 设置 MySQL 的用户与密码
        read_for "mysql user (default root): " "root" "37"
        MYSQL_USER="$READ_FOR_VAR"
        read_for "mysql ${MYSQL_USER} password: " "" "37"
        MYSQL_PASSWORD="$READ_FOR_VAR"
        
        mysql -u${MYSQL_USER} -p${MYSQL_PASSWORD} -e "show master status" > /dev/null
        
        echo "MYSQL_USER=${MYSQL_USER}" > /root/.backup-mysql.conf
        echo "MYSQL_PASSWORD=${MYSQL_PASSWORD}" >> /root/.backup-mysql.conf
        
        # 数据库完全备份
        echo "$(date +"%Y-%m-%d %H:%M:%S")" >> ${BACKUP_ROOT}/log/backup-mysql.log
        echo "----------------------------------------" >> ${BACKUP_ROOT}/log/backup-mysql.log
        backup-mysql full backup 2>> ${BACKUP_ROOT}/log/backup-mysql.log
        echo "----------------------------------------" >> ${BACKUP_ROOT}/log/backup-mysql.log
        echo "" >> ${BACKUP_ROOT}/log/backup-mysql.log
}

timer()
{
        echo timer
}

############################################################
#
#       6.次要操作
#
############################################################

############################################################
#
#       7.主要操作
#
############################################################
if [[ -z "$ARGUMENT1" ]]; then
        ARGUMENT1="timer"
fi

case "$ARGUMENT1" in
        "init")
                init
        ;;
        
        "timer")
                timer
        ;;
        
        *)
                default "$ARGUMENT1"
        ;;
esac

############################################################
#
#       8.结束语
#
############################################################
time_success
