#!/bin/bash

export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

############################################################
#
#       1.位置参量
#
############################################################
ARGUMENT1="$1"
ARGUMENT2="$2"
ARGUMENT3="$3"

set -eu
#set -x

echo_color()
{
        echo -e "\e[1m\e[40;$2m$1\e[0m"
}

echo_error()
{
        echo_color "$1" "31"
        exit 1
}

echo_warning()
{
        echo_color "$1" "33"
        sleep 5
}

if [[ "$(id -u)" != "0" ]]; then
        echo_error "Error: must run with root"
fi

if [[ -s "/usr/local/bin/myfunction.sh" ]]; then
        . /usr/local/bin/myfunction.sh
else
        echo_error "Error: myfunction.sh not found"
fi

############################################################
#
#       2.全局变量
#
############################################################
BACKUP_ROOT="/backup"
SOURCE_DIR="/"

############################################################
#
#       3.初始化
#
############################################################
mkdir -p ${BACKUP_ROOT}/{"centos-full","centos-incremental","log"}

############################################################
#
#       4.次要函数
#
############################################################

############################################################
#
#       5.主要函数
#
############################################################
default()
{
        echo "backup-centos: unrecognized option '$1'"
        
        echo "Usage: backup-centos <full|incr> <backup|restore> [list|DATE]"
        echo ""
        
        exit 1
}

# 增量备份
incremental_backup()
{
        BACKUP_TIME=$(date +"%Y-%m-%d-%H%M%S")
        
        rsync -avhzAHXP --delete -b --backup-dir=${BACKUP_ROOT}/centos-incremental/old-${BACKUP_TIME} \
        --exclude=${BACKUP_ROOT} --exclude={"/dev","/media","/mnt","/proc","/sys","/tmp"} \
        ${SOURCE_DIR} ${BACKUP_ROOT}/centos-incremental/latest
        
        echo "$BACKUP_TIME" > ${BACKUP_ROOT}/centos-incremental/.backup.time
}

# 增量恢复
incremental_restore()
{
        if [[ -d "${BACKUP_ROOT}/centos-incremental/latest" ]]; then
                rsync -avhAHXP ${BACKUP_ROOT}/centos-incremental/latest/ ${SOURCE_DIR}
        else
                echo_error "Error: incremental backup does not exist"
        fi
}

# 完全备份
full_backup()
{
        CURRENT_TIME=$(date +"%Y-%m-%d")
        
        if [[ ! -d "${BACKUP_ROOT}/centos-incremental/latest" ]] \
        || (  ! grep "$CURRENT_TIME" ${BACKUP_ROOT}/centos-incremental/.backup.time &> /dev/null ); then
                incremental_backup
                echo_warning "Warning: incremental backup complete"
        fi
        
        /usr/bin/cp -afvl ${BACKUP_ROOT}/centos-incremental/latest ${BACKUP_ROOT}/centos-full/$(date +"%Y-%m-%d-%H%M%S")
}

# 完全恢复
full_restore()
{
        :
}

# 完全恢复列表
full_restore_list()
{
        echo_color "=== centos full ===" "34"
        ls_timedir "${BACKUP_ROOT}/centos-full" "" ""
        
        exit 0
}

############################################################
#
#       6.次要操作
#
############################################################

############################################################
#
#       7.主要操作
#
############################################################
if [[ -z "$ARGUMENT1" ]]; then
        ARGUMENT1="incr"
fi

if [[ -z "$ARGUMENT2" ]]; then
        ARGUMENT2="backup"
fi

if [[ -z "$ARGUMENT3" ]]; then
        ARGUMENT3="list"
fi

case "$ARGUMENT1" in
        "full")
                case "$ARGUMENT2" in
                        "backup")
                                full_backup
                        ;;
                        
                        "restore")
                                case "$ARGUMENT3" in
                                        "list")
                                                full_restore_list
                                        ;;
                                        
                                        20[1-3][0-9]-[0-1][0-9]-[0-3][0-9]-[0-9][0-9][0-9][0-9][0-9][0-9])
                                                full_restore "$ARGUMENT3"
                                        ;;
                                        
                                        *)
                                                default "$ARGUMENT3"
                                        ;;
                                esac
                        ;;
                        
                        *)
                                default "$ARGUMENT2"
                        ;;
                esac
        ;;
        
        "incr")
                case "$ARGUMENT2" in
                        "backup")
                                incremental_backup
                        ;;
                        
                        "restore")
                                incremental_restore
                        ;;
                        
                        *)
                                default "$ARGUMENT2"
                        ;;
                esac
        ;;
        
        *)
                default "$ARGUMENT1"
        ;;
esac

############################################################
#
#       8.结束语
#
############################################################
time_success
