#!/bin/bash

export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

############################################################
#
#       1.位置参量
#
############################################################
ARGUMENT1="$1"

set -eu
#set -x

echo_color()
{
        echo -e "\e[1m\e[40;$2m$1\e[0m"
}

echo_error()
{
        echo_color "$1" "31"
        exit 1
}

echo_warning()
{
        echo_color "$1" "33"
        sleep 5
}

if [[ "$(id -u)" != "0" ]]; then
        echo_error "Error: must run with root"
fi

if [[ -s "/usr/local/bin/myfunction.sh" ]]; then
        . /usr/local/bin/myfunction.sh
else
        echo_error "Error: myfunction.sh not found"
fi

############################################################
#
#       2.全局变量
#
############################################################
BACKUP_ROOT="/backup"
MYSQL_LOG="${BACKUP_ROOT}/log/backup-mysql.log"
CENTOS_LOG="${BACKUP_ROOT}/log/backup-centos.log"

# 每月的第几天 $(date +"%d") 01 - 31
BACKUP_DAY="01"

# 每周的星期几 $(date +"%w")  0 - 6
BACKUP_WEEK="1"

############################################################
#
#       3.初始化
#
############################################################
# 同步时间
adjust_time
hwclock -w

############################################################
#
#       4.次要函数
#
############################################################

############################################################
#
#       5.主要函数
#
############################################################
default()
{
        echo "backup-policy: unrecognized option '$1'"
        
        echo "Usage: backup-policy [timer|init]"
        echo ""
        
        exit 1
}

init()
{
        # 完全备份数据库
        create_log "$MYSQL_LOG" "backup-mysql full backup"
        backup-mysql full backup 2>> "$MYSQL_LOG"
        
        # 增量备份数据库
        create_log "$MYSQL_LOG" "backup-mysql incr backup"
        backup-mysql incr backup 2>> "$MYSQL_LOG"
        
        # 增量备份操作系统
        create_log "$CENTOS_LOG" "backup-centos incr backup"
        backup-centos incr backup 2>> "$CENTOS_LOG"
        
        # 完全备份操作系统
        create_log "$CENTOS_LOG" "backup-centos full backup"
        backup-centos full backup 2>> "$CENTOS_LOG"
}

timer()
{
        # 完全备份数据库（每月几日）
        if [[ "$BACKUP_DAY" == "$(date +"%d")" ]]; then
                create_log "$MYSQL_LOG" "backup-mysql full backup"
                backup-mysql full backup 2>> "$MYSQL_LOG"
                sleep 3
        fi
        
        # 增量备份数据库（每天）
        create_log "$MYSQL_LOG" "backup-mysql incr backup"
        backup-mysql incr backup 2>> "$MYSQL_LOG"
        sleep 3
        
        # 增量备份操作系统（每天）
        create_log "$CENTOS_LOG" "backup-centos incr backup"
        backup-centos incr backup 2>> "$CENTOS_LOG"
        sleep 3
        
        # 完全备份操作系统（每月几日）
        if [[ "$BACKUP_DAY" == "$(date +"%d")" ]]; then
                create_log "$CENTOS_LOG" "backup-centos full backup"
                backup-centos full backup 2>> "$CENTOS_LOG"
                sleep 3
        fi
        
        # 重启服务器（每周几）
        if [[ "$BACKUP_WEEK" == "$(date +"%w")" ]]; then
                shutdown -r +3
        fi
}

############################################################
#
#       6.次要操作
#
############################################################

############################################################
#
#       7.主要操作
#
############################################################
if [[ -z "$ARGUMENT1" ]]; then
        ARGUMENT1="timer"
fi

case "$ARGUMENT1" in
        "init")
                init
        ;;
        
        "timer")
                timer
        ;;
        
        *)
                default "$ARGUMENT1"
        ;;
esac

############################################################
#
#       8.结束语
#
############################################################
time_success
