#!/bin/bash

export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

############################################################
#
#       1.位置参量
#
############################################################
ARGUMENT1="$1"
ARGUMENT2="$2"
ARGUMENT3="$3"

set -eu
#set -x

echo_color()
{
        echo -e "\e[1m\e[40;$2m$1\e[0m"
}

echo_error()
{
        echo_color "$1" "31"
        exit 1
}

echo_warning()
{
        echo_color "$1" "33"
        sleep 5
}

if [[ "$(id -u)" != "0" ]]; then
        echo_error "Error: must run with root"
fi

if [[ -s "/usr/local/bin/myfunction.sh" ]]; then
        . /usr/local/bin/myfunction.sh
else
        echo_error "Error: myfunction.sh not found"
fi

############################################################
#
#       2.全局变量
#
############################################################

############################################################
#
#       3.初始化
#
############################################################

############################################################
#
#       4.次要函数
#
############################################################

############################################################
#
#       5.主要函数
#
############################################################
default()
{
        echo 0
}

full_backup()
{
        echo 1
}

full_restore()
{
        echo 2
}

full_restore_list()
{
        echo 3
}

incremental_backup()
{
        echo 11
}

incremental_restore()
{
        echo 22
}

incremental_restore_list()
{
        echo 33
}

############################################################
#
#       6.次要操作
#
############################################################

############################################################
#
#       7.主要操作
#
############################################################
case "$ARGUMENT1" in
        "full")
                case "$ARGUMENT2" in
                        "backup")
                                full_backup
                        ;;
                        
                        "restore")
                                case "$ARGUMENT3" in
                                        "list")
                                                full_restore_list
                                        ;;
                                        
                                        20[1-3][0-9]-[0-1][0-9]-[0-3][0-9]-[0-9][0-9][0-9][0-9][0-9][0-9])
                                                full_restore "$ARGUMENT3"
                                        ;;
                                        
                                        *)
                                                default "$ARGUMENT3"
                                        ;;
                                esac
                        ;;
                        
                        *)
                                default "$ARGUMENT2"
                        ;;
                esac
        ;;
        
        "incr")
                case "$ARGUMENT2" in
                        "backup")
                                incremental_backup
                        ;;
                        
                        "restore")
                                case "$ARGUMENT3" in
                                        "list")
                                                incremental_restore_list
                                        ;;
                                        
                                        20[1-3][0-9]-[0-1][0-9]-[0-3][0-9]-[0-9][0-9][0-9][0-9][0-9][0-9])
                                                incremental_restore "$ARGUMENT3"
                                        ;;
                                        
                                        *)
                                                default "$ARGUMENT3"
                                        ;;
                                esac
                        ;;
                        
                        *)
                                default "$ARGUMENT2"
                        ;;
                esac
        ;;
        
        *)
                default "$ARGUMENT1"
        ;;
esac

############################################################
#
#       8.结束语
#
############################################################
time_success
