#!/bin/bash

export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

############################################################
#
#       位置参量
#
############################################################
ARGUMENT1="$1"
ARGUMENT2="$2"
ARGUMENT3="$3"

set -eu
#set -x

if [[ "$(id -u)" != "0" ]]; then
        echo "Error: must run with root"
        exit 1
fi

############################################################
#
#       全局变量
#
############################################################
BACKUP_ROOT="/backup"
BACKUP_DIR="mysql"
LOG_DIR="log"

############################################################
#
#       处理变量
#
############################################################

############################################################
#
#       主要函数
#
############################################################

############################################################
#
#       主要操作
#
############################################################
mkdir -p ${BACKUP_ROOT}/{"$BACKUP_DIR","$LOG_DIR"}

case "$ARGUMENT1" in
        
        "full")
                
                case "$ARGUMENT2" in
                        
                        "backup")
                                full_backup
                          ;;
                        
                        "restore")
                                
                                case "$ARGUMENT3" in
                                        
                                        "list")
                                                full_backup_list
                                          ;;
                                        
                                        20[1-3][0-9]-[0-1][0-9]-[0-3][0-9]-[0-9][0-9][0-9][0-9][0-9][0-9])
                                                full_restore "$ARGUMENT3"
                                          ;;
                                        
                                        *)
                                                default "$ARGUMENT3"
                                          ;;
                                        
                                esac
                                
                          ;;
                        
                        *)
                                default "$ARGUMENT2"
                          ;;
                        
                esac
                
          ;;
        
        "incremental")
                
                case "$ARGUMENT2" in
                        
                        "backup")
                                incremental_backup
                          ;;
                        
                        "restore")
                                
                                case "$ARGUMENT3" in
                                        
                                        "list")
                                                incremental_backup_list
                                          ;;
                                        
                                        20[1-3][0-9]-[0-1][0-9]-[0-3][0-9]-[0-9][0-9][0-9][0-9][0-9][0-9])
                                                incremental_restore "$ARGUMENT3"
                                          ;;
                                        
                                        *)
                                                default "$ARGUMENT3"
                                          ;;
                                        
                                esac
                                
                          ;;
                        
                        *)
                                default "$ARGUMENT2"
                          ;;
                        
                esac
                
          ;;
        
        *)
                default "$ARGUMENT1"
          ;;
        
esac
