#!/bin/bash

# caw [ --curl|--axel|--wget --remove|--hold --dir=DIR --md5=MD5 ] URL
# caw [ -c|-a|-w -r|-h -d DIR -m MD5 ] URL

export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

############################################################
#
#       1.位置参量
#
############################################################

set -eu
#set -x

echo_color()
{
        echo -e "\e[1m\e[40;$2m$1\e[0m"
}

echo_error()
{
        echo_color "$1" "31"
        exit 1
}

echo_warning()
{
        echo_color "$1" "33"
        sleep 5
}

if [[ "$(id -u)" != "0" ]]; then
        echo_error "Error: must run with root"
fi

if [[ -s "/usr/local/bin/option.sh" ]]; then
        . /usr/local/bin/option.sh
else
        echo_error "Error: option.sh not found"
fi

############################################################
#
#       2.全局变量
#
############################################################
# 定义指令参数的个数
COMMAND_ARGUMENT_NUMBER="1"

URL=$(command_argument1 "$@")
FILE=
MD5=
DIR=$(pwd)
HOLD_REMOVE="remove"
TOOLS="curl"

ALL_LONG_OPTION=$(long_option "$@")
ALL_SHORT_OPTION=$(short_option "$@")

############################################################
#
#       3.初始化
#
############################################################
# 检测 URL
if [[ -n "$URL" ]] && ( echo "$URL" | grep "^http[s]*://." &> /dev/null ); then
        FILE=$( echo "$URL" | awk -F/ '{ if (NF>3) { print $NF } }' )
else
        echo_error "Error: caw missing url"
fi

# 检测 FILE
if [[ -z "$FILE" ]]; then
        echo_error "Error: caw url error"
fi

# 获取 MD5
if ( echo "$ALL_LONG_OPTION" | grep "^--md5$" &> /dev/null ) && [[ -n "$(long_argument "--md5" "$@")" ]]; then
        MD5=$(long_argument "--md5" "$@")
elif ( echo "$ALL_SHORT_OPTION" | grep "^-m$" &> /dev/null ) && [[ -n "$(short_argument "-m" "$@")" ]]; then
        MD5=$(short_argument "-m" "$@")
else
        :
fi

#
echo "$MD5"
############################################################
#
#       4.次要函数
#
############################################################

############################################################
#
#       5.主要函数
#
############################################################

############################################################
#
#       6.次要操作
#
############################################################

############################################################
#
#       7.主要操作
#
############################################################

############################################################
#
#       8.结束语
#
############################################################
