#!/bin/bash

export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

############################################################
#
#       1.位置参量
#
############################################################

set -eu
#set -x

echo_color()
{
        echo -e "\e[1m\e[40;$2m$1\e[0m"
}

echo_error()
{
        echo_color "$1" "31"
        exit 1
}

echo_warning()
{
        echo_color "$1" "33"
        sleep 5
}

if [[ "$(id -u)" != "0" ]]; then
        echo_error "Error: must run with root"
fi

if [[ -s "/usr/local/bin/myfunction.sh" ]]; then
        . /usr/local/bin/myfunction.sh
else
        echo_error "Error: myfunction.sh not found"
fi

############################################################
#
#       2.全局变量
#
############################################################
IP_ADDR=$(ip_addr)
HOST_NAME="laravel"

############################################################
#
#       3.初始化
#
############################################################
if [[ ! -s "$MYSQL_CONF" ]]; then
        yum -y install screen
        clear
        
        mysql_root
        clear
        
        echo_line "run command: " "35"
        echo_color "(1)  screen -S laravel" "35"
        echo_color "             (2)  config-centos" "35"
        echo_color "             (3)  install-lnmp" "35"
        
        echo ""
        exit 0
fi

############################################################
#
#       4.次要函数
#
############################################################

############################################################
#
#       5.主要函数
#
############################################################

############################################################
#
#       6.次要操作
#
############################################################

############################################################
#
#       7.主要操作
#
############################################################
#
cat > /etc/sysconfig/network <<-EOF
NETWORKING=yes
HOSTNAME=${HOST_NAME}
EOF

#
sed -i "/^10\./d"  /etc/hosts
sed -i "/^172\./d" /etc/hosts
sed -i "/^192\./d" /etc/hosts

echo "${IP_ADDR} ${HOST_NAME}" >> /etc/hosts

#
if ( sestatus -v | grep "SELinux status: *enabled" &> /dev/null ); then
        setenforce 0
        
        sed -i "s/^SELINUX=enforcing/SELINUX=disabled/g"  /etc/selinux/config
        sed -i "s/^SELINUX=permissive/SELINUX=disabled/g" /etc/selinux/config
fi

#
if [[ -f "/etc/yum.repos.d/epel.repo" ]]; then
        rm -rf /etc/yum.repos.d/epel.repo
fi

if [[ -s "/root/myfile/epel.repo" ]]; then
        mv /root/myfile/epel.repo /etc/yum.repos.d/epel.repo
else
        echo_error "Error: epel.repo not found"
fi

#
yum clean all && yum makecache

#
for (( NUM=0; NUM < 5; NUM++ )); do
        yum -y install ntpdate vim-enhanced screen wget axel nmap net-tools tree git psmisc \
        gcc gcc-c++ autoconf automake ncurses-devel libtool \
        redis rsync
done

#
adjust_time
hwclock -w

#
yum -y update && yum -y upgrade

#
for SERVICE in "postfix"; do
        systemctl stop    ${SERVICE}
        systemctl disable ${SERVICE}
done

#
systemctl restart firewalld
sleep 3

for SERVICE in "redis" "crond"; do
        systemctl restart ${SERVICE}
        systemctl enable  ${SERVICE}
done

if ( ! firewall-cmd --list-port | grep 6379 &> /dev/null ); then
        firewall-cmd --zone=public --add-port=6379/tcp --permanent
fi

systemctl restart firewalld
sleep 3

#
sed -i "/^[0-9]/d" /etc/crontab
echo "0 5 * * * root /usr/local/bin/backup-policy &> /dev/null" >> /etc/crontab

############################################################
#
#       8.结束语
#
############################################################
time_success
