#!/bin/bash

export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

############################################################
#
#       1.位置参量
#
############################################################

set -eu
#set -x

echo_color()
{
        echo -e "\e[1m\e[40;$2m$1\e[0m"
}

echo_error()
{
        echo_color "$1" "31"
        exit 1
}

echo_warning()
{
        echo_color "$1" "33"
        sleep 5
}

if [[ "$(id -u)" != "0" ]]; then
        echo_error "Error: must run with root"
fi

if [[ -s "/usr/local/bin/myfunction.sh" ]]; then
        . /usr/local/bin/myfunction.sh
else
        echo_error "Error: myfunction.sh not found"
fi

############################################################
#
#       2.全局变量
#
############################################################
LOCK="/root/.network.lock"
CONF="/root/network.conf"
DEVICE_LIST=$(find /etc/sysconfig/network-scripts -name "ifcfg-enp*" -type f | xargs)
CONFIG_FILE_LIST="${LOCK}
                  ${DEVICE_LIST}
                  /etc/hosts
                  /root/myfile/settings
                  /root/myfile/dhcp.template
                  /root/myfile/dhcpd.conf
                  /root/myfile/sample_end.ks
                  /etc/cobbler/settings
                  /etc/cobbler/dhcp.template
                  /etc/dhcp/dhcpd.conf
                  /var/lib/cobbler/kickstarts/sample_end.ks
                 "

############################################################
#
#       3.初始化
#
############################################################

############################################################
#
#       4.次要函数
#
############################################################

############################################################
#
#       5.主要函数
#
############################################################

############################################################
#
#       6.次要操作
#
############################################################

############################################################
#
#       7.主要操作
#
############################################################
#
if [[ ! -s "$LOCK" ]]; then
        echo "OLD_IPADDR=192.168.1.5" > "$LOCK"
        echo "OLD_GATEWAY=192.168.1.1" >> "$LOCK"
        echo "OLD_LAN=192.168.1" >> "$LOCK"
fi

. "$LOCK"

#
if [[ ! -s "$CONF" ]]; then
        echo "NEW_IPADDR=" > "$CONF"
        echo "NEW_GATEWAY=" >> "$CONF"
        echo_error "Error: Setting the ip and gateway in ${CONF}"
fi

while read LINE; do
        
        if ( ! echo "$LINE" | grep "=10\.[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*$" &> /dev/null ) \
        && ( ! echo "$LINE" | grep "=172\.[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*$" &> /dev/null ) \
        && ( ! echo "$LINE" | grep "=192\.[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*$" &> /dev/null ) \
        && [[ -n "$LINE" ]]; then
                
                echo_error "Error: Setting the ip and gateway in ${CONF}"
        fi
        
done < ${CONF}

. ${CONF}

#
NEW_LAN=$(echo "$NEW_GATEWAY" | sed "s/\.[0-9][0-9]*$//g")

#
for CONFIG_FILE in ${CONFIG_FILE_LIST}; do
        
        if [[ -s "$CONFIG_FILE" ]]; then
                sed -i "s/${OLD_IPADDR}/${NEW_IPADDR}/g" ${CONFIG_FILE}
                sed -i "s/${OLD_GATEWAY}/${NEW_GATEWAY}/g" ${CONFIG_FILE}
                sed -i "s/${OLD_LAN}/${NEW_LAN}/g" ${CONFIG_FILE}
        fi
        
done

#
echo "ip addr: ${OLD_IPADDR} => ${NEW_IPADDR}"
echo "gateway: ${OLD_GATEWAY} => ${NEW_GATEWAY}"

############################################################
#
#       8.结束语
#
############################################################
