#!/bin/bash

export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

############################################################
#
#       1.位置参量
#
############################################################

set -eu
#set -x

echo_color()
{
        echo -e "\e[1m\e[40;$2m$1\e[0m"
}

echo_error()
{
        echo_color "$1" "31"
        exit 1
}

echo_warning()
{
        echo_color "$1" "33"
        sleep 5
}

if [[ "$(id -u)" != "0" ]]; then
        echo_error "Error: must run with root"
fi

if [[ -s "/usr/local/bin/myfunction.sh" ]]; then
        . /usr/local/bin/myfunction.sh
else
        echo_error "Error: myfunction.sh not found"
fi

############################################################
#
#       2.全局变量
#
############################################################
ONEKEY_LOG="/root/one-key.log"

############################################################
#
#       3.初始化
#
############################################################
export PATH=$PATH:/root/bin

############################################################
#
#       4.次要函数
#
############################################################

############################################################
#
#       5.主要函数
#
############################################################

############################################################
#
#       6.次要操作
#
############################################################

############################################################
#
#       7.主要操作
#
############################################################
#
clear
countdown "13" " "

#
create_log "$ONEKEY_LOG" "config-centos"
config-centos 2>> "$ONEKEY_LOG"

#
create_log "$ONEKEY_LOG" "install-lnmp"
install-lnmp 2>> "$ONEKEY_LOG"

#
create_log "$ONEKEY_LOG" "backup-policy init"
backup-policy init 2>> "$ONEKEY_LOG"

############################################################
#
#       8.结束语
#
############################################################
time_success

curl -sS http://git.oschina.net/quefei/mycommand/raw/master/uninstall_part.sh | bash
