#!/bin/bash

export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

set -eu
#set -x

echo_color()
{
        echo -e "\e[1m\e[40;$2m$1\e[0m"
}

echo_error()
{
        echo_color "$1" "31"
        exit 1
}

echo_warning()
{
        echo_color "$1" "33"
        sleep 5
}

if [[ "$(id -u)" != "0" ]]; then
        echo_error "Error: must run with root"
fi

if [[ -s "/usr/local/bin/myfunction.sh" ]]; then
        . /usr/local/bin/myfunction.sh
else
        echo_error "Error: myfunction.sh not found"
fi

# 全局变量
LARAVEL_ROOT="/usr/local/nginx/html/laravel"
ENV_OPTION_LIST="CACHE_DRIVER
                 DB_CONNECTION
                 DB_HOST
                 DB_PORT
                 DB_DATABASE
                 DB_USERNAME
                 DB_PASSWORD
                "

# 创建 .my.cnf
mysql_create

# 创建数据库
mysql -e "create database ${MYSQL_DATABASE}"

# 配置 .env
for ENV_OPTION in ${ENV_OPTION_LIST}; do
        sed -i "/^${ENV_OPTION}=/d" ${LARAVEL_ROOT}/.env
done

sed -i "/^$/d" ${LARAVEL_ROOT}/.env

cat >> ${LARAVEL_ROOT}/.env <<-EOF

CACHE_DRIVER=array

DB_CONNECTION=mysql
DB_HOST=localhost
DB_PORT=3306
DB_DATABASE=${MYSQL_DATABASE}
DB_USERNAME=${MYSQL_USER}
DB_PASSWORD=${MYSQL_PASSWORD}

EOF

# 安装 Laravel Mix
cd ${LARAVEL_ROOT}

for (( NUM=0; NUM < 5; NUM++ )); do
        cnpm install && break 1 || true
done

# 结束
mysql_remove
time_success
