#!/bin/bash

export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

############################################################
#
#       1.位置参量
#
############################################################

set -eu
#set -x

echo_color()
{
        echo -e "\e[1m\e[40;$2m$1\e[0m"
}

echo_error()
{
        echo_color "$1" "31"
        exit 1
}

echo_warning()
{
        echo_color "$1" "33"
        sleep 5
}

if [[ "$(id -u)" != "0" ]]; then
        echo_error "Error: must run with root"
fi

if [[ -s "/usr/local/bin/myfunction.sh" ]]; then
        . /usr/local/bin/myfunction.sh
else
        echo_error "Error: myfunction.sh not found"
fi

############################################################
#
#       2.全局变量
#
############################################################
LNMP_ORG="lnmp1.4.tar.gz"
LNMP_DIR="/usr/local/src/lnmp1.4"

MYSQL_VERSION="4"
MYSQL_INNODB="Y"
PHP_VERSION="7"
MEMORY_ALLOCATOR="1"

############################################################
#
#       3.初始化
#
############################################################

############################################################
#
#       4.次要函数
#
############################################################

############################################################
#
#       5.主要函数
#
############################################################

############################################################
#
#       6.次要操作
#
############################################################

############################################################
#
#       7.主要操作
#
############################################################
#
mysql_create

#
if [[ -f "/usr/local/src/${LNMP_ORG}" ]]; then
        rm -rf /usr/local/src/${LNMP_ORG}
fi

if [[ -s "/root/myfile/${LNMP_ORG}" ]]; then
        mv /root/myfile/${LNMP_ORG} /usr/local/src/${LNMP_ORG}
else
        echo_error "Error: ${LNMP_ORG} not found"
fi

#
if [[ -d "$LNMP_DIR" ]]; then
        mv ${LNMP_DIR} ${LNMP_DIR}.bak.$(date +"%Y%m%d%H%M%S")
fi

tar -xzvf /usr/local/src/${LNMP_ORG} -C /usr/local/src

#cd ${LNMP_DIR}

# 实现 LNMP 自动退出
sed -i "/Install lnmp.*completed.*enjoy it/a\    ###################################" ${LNMP_DIR}/include/end.sh

sed -i "/Install lnmp.*completed.*enjoy it/a\        sleep 60; killall tee; exit" ${LNMP_DIR}/include/end.sh

sed -i "/Install lnmp.*completed.*enjoy it/a\    ###################################" ${LNMP_DIR}/include/end.sh

#
VAR1="$MYSQL_VERSION"
VAR2="$MYSQL_PASSWORD"
VAR3="$MYSQL_INNODB"
VAR4="$PHP_VERSION"
VAR5="$MEMORY_ALLOCATOR"

bash ${LNMP_DIR}/install.sh lnmp <<-EOF
${VAR1}
${VAR2}
${VAR3}
${VAR4}
${VAR5}
EOF

#
touch /usr/local/nginx/logs/access.log























#cd - &> /dev/null

############################################################
#
#       8.结束语
#
############################################################
mysql_remove
