#!/bin/bash

export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

############################################################
#
#       1.位置参量
#
############################################################

set -eu
#set -x

echo_color()
{
        echo -e "\e[1m\e[40;$2m$1\e[0m"
}

echo_error()
{
        echo_color "$1" "31"
        exit 1
}

echo_warning()
{
        echo_color "$1" "33"
        sleep 5
}

if [[ "$(id -u)" != "0" ]]; then
        echo_error "Error: must run with root"
fi

if [[ -s "/usr/local/bin/myfunction.sh" ]]; then
        . /usr/local/bin/myfunction.sh
else
        echo_error "Error: myfunction.sh not found"
fi

############################################################
#
#       2.全局变量
#
############################################################
SERVICE_LIST="cobblerd rsyncd httpd xinetd tftp"

CONFIG_FILE_LIST="/etc/xinetd.d/tftp
                  /etc/cobbler/settings
                  /etc/cobbler/dhcp.template
                  /etc/cobbler/pxe/pxedefault.template
                  /etc/cobbler/pxe/pxeprofile.template
                  /etc/dhcp/dhcpd.conf
                 "

############################################################
#
#       3.初始化
#
############################################################

############################################################
#
#       4.次要函数
#
############################################################

############################################################
#
#       5.主要函数
#
############################################################

############################################################
#
#       6.次要操作
#
############################################################

############################################################
#
#       7.主要操作
#
############################################################
#
if [[ -x "/etc/init.d/nginx" ]]; then
        /etc/init.d/nginx stop || true
        chmod 644 /etc/init.d/nginx
        echo_warning "Warning: /etc/init.d/nginx is disabled"
fi

#
for (( NUM=0; NUM < 5; NUM++ )); do
        yum -y install dhcp tftp-server syslinux httpd xinetd cobbler pykickstart cobbler-web fence-agents \
        rsync wget axel
done

#
for SERVICE in ${SERVICE_LIST}; do
        systemctl restart ${SERVICE}
        systemctl enable  ${SERVICE}
        sleep 3
done

#
for (( NUM=0; NUM < 5; NUM++ )); do
        cobbler get-loaders || true
done

#
for CONFIG_FILE_PATH in ${CONFIG_FILE_LIST}; do
        
        if [[ -f "$CONFIG_FILE_PATH" ]]; then
                mv ${CONFIG_FILE_PATH} ${CONFIG_FILE_PATH}.bak.$(date +"%Y%m%d%H%M%S")
        fi
        
        CONFIG_FILE=$(path_file "$CONFIG_FILE_PATH")
        
        if [[ -s "/root/myfile/${CONFIG_FILE}" ]]; then
                mv /root/myfile/${CONFIG_FILE} ${CONFIG_FILE_PATH}
        else
                echo_error "Error: ${CONFIG_FILE} not found"
        fi
        
done

#
for (( NUM=0; NUM < 5; NUM++ )); do
        cobbler sync || true
done

systemctl restart cobblerd
sleep 3

#
systemctl restart dhcpd
systemctl enable  dhcpd
sleep 3

#
for (( NUM=0; NUM < 5; NUM++ )); do
        cobbler sync || true
done

systemctl restart cobblerd
sleep 3

############################################################
#
#       8.结束语
#
############################################################
time_success
