#!/bin/bash

export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

set -e
#set -u
#set -x

echo_color()
{
        echo -e "\e[1m\e[40;$2m$1\e[0m"
}

echo_error()
{
        echo_color "$1" "31"
        exit 1
}

echo_warning()
{
        echo_color "$1" "33"
        sleep 5
}

if [[ "$(id -u)" != "0" ]]; then
        echo_error "Error: must run with root"
fi

if [[ -s "/usr/local/bin/myfunction.sh" ]]; then
        . /usr/local/bin/myfunction.sh
else
        echo_error "Error: myfunction.sh not found"
fi

# 全局变量
NODE_VERSION="node-v8.4.0"

# 安装 tvm 或者 tnvm
wget -O- https://raw.githubusercontent.com/aliyun-node/tnvm/master/install.sh | bash

export TNVM_DIR="/root/.tnvm"

# This loads nvm
if [[ -s "${TNVM_DIR}/tnvm.sh" ]]; then
        . ${TNVM_DIR}/tnvm.sh
fi

# 安装 node 自带 npm
tnvm install "$NODE_VERSION"

tnvm use "$NODE_VERSION"

# 安装 cnpm
for (( NUM=0; NUM < 5; NUM++ )); do
        npm install -g cnpm --registry=https://registry.npm.taobao.org && break 1 || true
done

# 安装 yarn
cnpm install -g yarn

yarn config set registry 'https://registry.npm.taobao.org'

# 结束
time_success
