#!/bin/bash

export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

set -eu
#set -x

echo_color()
{
        echo -e "\e[1m\e[40;$2m$1\e[0m"
}

echo_error()
{
        echo_color "$1" "31"
        exit 1
}

echo_warning()
{
        echo_color "$1" "33"
        sleep 5
}

if [[ "$(id -u)" != "0" ]]; then
        echo_error "Error: must run with root"
fi

if [[ -s "/usr/local/bin/myfunction.sh" ]]; then
        . /usr/local/bin/myfunction.sh
else
        echo_error "Error: myfunction.sh not found"
fi

# 全局变量
LARAVEL_ROOT="/usr/local/nginx/html/laravel"

# 安装 composer
if [[ -f "/usr/local/bin/composer" ]]; then
        rm -rf /usr/local/bin/composer
fi

if [[ -x "/root/myfile/composer" ]]; then
        mv /root/myfile/composer /usr/local/bin/composer
else
        echo_error "Error: composer not found"
fi

composer config -g repo.packagist composer https://packagist.phpcomposer.com

composer self-update

# 安装 Laravel
cd /usr/local/nginx/html

if [[ -d "$LARAVEL_ROOT" ]]; then
        mv ${LARAVEL_ROOT} ${LARAVEL_ROOT}.bak.$(date +"%Y%m%d%H%M%S")
fi

composer create-project --prefer-dist laravel/laravel

chown -R www:www ${LARAVEL_ROOT}

if [[ -f "/laravel" ]]; then
        rm -rf /laravel
fi

ln -s ${LARAVEL_ROOT} /laravel

# 安装语言包
cd ${LARAVEL_ROOT}
composer require caouecs/laravel-lang:~3.0

if [[ -d "${LARAVEL_ROOT}/vendor/caouecs/laravel-lang/src/zh-CN" ]] \
&& [[ ! -d "${LARAVEL_ROOT}/resources/lang/zh-CN" ]]; then
        cp -r ${LARAVEL_ROOT}/vendor/caouecs/laravel-lang/src/zh-CN ${LARAVEL_ROOT}/resources/lang
fi

# 配置 Laravel
sed -i "s/'timezone' *=> *'UTC',/'timezone' => 'Asia\/Shanghai',/g" ${LARAVEL_ROOT}/config/app.php
sed -i "s/'locale' *=> *'en',/'locale' => 'zh-CN',/g"               ${LARAVEL_ROOT}/config/app.php
sed -i "s/'lifetime' *=> *120,/'lifetime' => 30,/g"                 ${LARAVEL_ROOT}/config/session.php

# 结束
time_success
