#!/bin/bash
export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

echoColor()      { echo -e "\e[1m\e[$3;$2m$1\e[0m"; }
echoLine()       { echo -n $(echoColor "$1" "$2" "$3" ); }
echoSuccess()    { echo $(echoLine "Success: " "32" "40")$(echoColor "$1" "37" "40"); }
echoWarning()    { echo $(echoLine "Warning: " "33" "40")$(echoColor "$1" "37" "40"); }
echoError()      { echo $(echoLine "Error: " "31" "40")$(echoColor "$1" "37" "40"); }
displaySuccess() { echo $(echoColor "Success" "32" "40"); }
displayError()   { echo $(echoColor "Error" "31" "40"); }

if [ $(id -u) != "0" ]; then
    echoError "must run with root"; exit 1
fi

# 例如：mydir "路径"; mydir "路径" -f

# 获取文件与目录
Path=$1

if [[ $Path == "" ]]; then
    echoError "mydir missing operand"
    exit 1
fi

File=$(echo $Path | awk -F/ '{ print $NF }')
Directory=$(echo $Path | sed "s/$File$//g")

if [[ $2 == "-f" ]]; then
    echo $File
else
    echo $Directory
fi
