#!/bin/bash
export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

echoSuccess()    { echo -n -e "\e[0;32mSuccess: \e[0m"; echo $1; }
echoWarning()    { echo -n -e "\e[0;33mWarning: \e[0m"; echo $1; }
echoError()      { echo -n -e "\e[0;31mError: \e[0m"; echo $1; }
displaySuccess() { echo -e "\e[0;32mSuccess\e[0m"; }
displayError()   { echo -e "\e[0;31mError\e[0m"; }

if [ $(id -u) != "0" ]; then
    echoError "must run with root"; exit 1
fi

#
if [ -f /usr/local/bin/myfunction.sh ]; then
    . /usr/local/bin/myfunction.sh
else
    echoError "myfunction.sh not found"
    exit 1
fi

# 批量下载
Value=10

if ( echo "$*" | grep "[ \t]-f[ \t]" &> /dev/null ); then
    echoSuccess "-f"
elif ( echo "$*" | grep "[ \t]-d[ \t]" &> /dev/null ); then
    echoSuccess "-d"
elif ( echo "$*" | grep "[ \t]--md5[ \t]" &> /dev/null ); then
    echoSuccess "md5"
elif ( echo "$*" | grep "[ \t]--no[ \t]" &> /dev/null ); then
    echoSuccess "no"
elif ( echo "$*" | grep "[ \t]--wget[ \t]" &> /dev/null ); then
    echoSuccess "wget"
elif ( echo "$*" | grep "[ \t]http" &> /dev/null ); then
    echoSuccess "url"
else
    echoSuccess "else"
fi



























































































