#!/bin/bash
export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

echoSuccess()    { echo -n -e "\e[0;32mSuccess: \e[0m"; echo $1; }
echoWarning()    { echo -n -e "\e[0;33mWarning: \e[0m"; echo $1; }
echoError()      { echo -n -e "\e[0;31mError: \e[0m"; echo $1; }
displaySuccess() { echo -e "\e[0;32mSuccess\e[0m"; }
displayError()   { echo -e "\e[0;31mError\e[0m"; }

if [ $(id -u) != "0" ]; then
    echoError "must run with root"; exit 1
fi

#
if [ -f /usr/local/bin/myfunction.sh ]; then
    . /usr/local/bin/myfunction.sh
else
    echoError "myfunction.sh not found"
    exit 1
fi

# 例如：mydown "URL/文件"
# 例如：mydown -f "文件" -d "目录" --md5 "MD5" --no --wget "URL"
# 例如：mydown -f "文件1 文件2 文件3" -d "目录" --md5 "MD5" --no --wget "URL"

# 批量下载
# 获取选项
Value=10

Option=$(IFS=: && echo ":$*:")

FileList=$(echo $Option | grep ":-f:" | awk -F":-f:" '{ print $2 }' | awk -F: '{ print $1 }')
Directory=$(echo $Option | grep ":-d:" | awk -F":-d:" '{ print $2 }' | awk -F: '{ print $1 }')
Md5=$(echo $Option | grep ":--md5:" | awk -F":--md5:" '{ print $2 }' | awk -F: '{ print $1 }')

UrlHead=$(echo $Option | grep ":http[s]*://" | awk -F":htt" '{ print $2 }' | awk -F: '{ print $1 }')
UrlTail=$(echo $Option | grep ":http[s]*://" | awk -F":htt" '{ print $2 }' | awk -F: '{ print $2 }')
echo $Option | grep ":http[s]*://" &> /dev/null && Url="htt$UrlHead:$UrlTail"

echo $Option | grep ":--no:" &> /dev/null && Change="--no"
echo $Option | grep ":--wget:" &> /dev/null && Download="--wget"

Url=$(echo $Url | sed "s/\/$//g")
FileList=$(echo $FileList | sed "s/^\///g")
FileList=$(echo $FileList | sed "s/[ \t]\// /g")

# 处理选项
if [[ $Url == "" ]]; then
    echoError "mydown missing URL"
    exit 1
fi

if [[ $FileList == "" ]]; then
    FileList=$(echo $Url | awk -F/ '{ print $NF }')
    Url=$(echo $Url | sed "s/\/$FileList$//g")
fi

if [[ $Directory == "" ]]; then
    Directory=$(pwd)
fi

# 检测命令是否存在
checkCommand "mypath mymake" || exit 1

Directory=$(mypath $Directory)

for File in $FileList; do
    
    # 默认删除旧文件
    if [[ $Change != "--no" ]]; then
        [ -f $Directory/$File ] && rm -rf $Directory/$File
    fi
    
    for (( i = 0; i < Value; i++ )); do
        
        if [ -s $Directory/$File ]; then
            
            # 如果 MD5 存在就检验 MD5，默认不检验
            if [[ $Md5 != "" ]]; then
                
                if [[ $Md5 == $(md5sum $Directory/$File | awk '{ print $1 }') ]]; then
                    break 1
                else
                    rm -rf $Directory/$File
                fi
                
            else
                break 1
            fi
            
        else
            
            # 创建目录
            mymake $Directory/$File || exit 1
            
            # 使用 wget 下载，如果 wget 不存在就安装它
            if [[ $Download == "--wget" ]]; then
                
                if ( checkCommand wget &> /dev/null ); then
                    :
                else
                    for (( a = 0; a < 5; a++ )); do
                        yum -y install wget
                    done
                    
                    checkCommand wget || exit 1
                fi
                
                FileHead=$(filePath $File)
                
                wget -c -P $Directory/$FileHead $Url/$File
                
            else
                # 默认使用 curl 下载
                curl -o $Directory/$File $Url/$File
                
            fi
            
        fi
        
    done
    
    FileTail=$(filePath $File -f)
    
    # 下载失败
    if (( i == Value )); then
        echoError "$FileTail download failed"
        exit 1
    fi
    
    # 下载的文件不存在
    if [[ $Download != "--wget" ]]; then
        if ( grep "<title>.*404.*</title>" $Directory/$File &> /dev/null ); then
            mv $Directory/$File $Directory/$File-404-$(date +"%Y%m%d%H%M%S")
            echoWarning "$FileTail not found - 404"
        fi
    fi
    
done

displaySuccess
