#!/bin/bash
export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

echoColor()      { echo -e "\e[1m\e[$3;$2m$1\e[0m"; }
echoLine()       { echo -n $(echoColor "$1" "$2" "$3" ); }
echoSuccess()    { echo $(echoLine "Success: " "32" "40")$(echoColor "$1" "37" "40"); }
echoWarning()    { echo $(echoLine "Warning: " "33" "40")$(echoColor "$1" "37" "40"); }
echoError()      { echo $(echoLine "Error: " "31" "40")$(echoColor "$1" "37" "40"); }
displaySuccess() { echo $(echoColor "Success" "32" "40"); }
displayError()   { echo $(echoColor "Error" "31" "40"); }

if [ $(id -u) != "0" ]; then
    echoError "must run with root"; exit 1
fi

#
String=$1
Delimiter=$2

if [[ $Delimiter == "" ]]; then
    Delimiter=" "
fi

LetterList="A B C D E F G H I J K L M N O P Q R S T U V W X Y Z \
            a b c d e f g h i j k l m n o p q r s t u v w x y z \
            0 1 2 3 4 5 6 7 8 9 \
            - _"

for Letter in $LetterList; do
    String=$(echo $String | sed "s/$Letter/$Letter$Delimiter/g")
done

echo $String
