#!/bin/bash
export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

echoSuccess()    { echo -n -e "\e[0;32mSuccess: \e[0m"; echo $1; }
echoWarning()    { echo -n -e "\e[0;33mWarning: \e[0m"; echo $1; }
echoError()      { echo -n -e "\e[0;31mError: \e[0m"; echo $1; }
displaySuccess() { echo -e "\e[0;32mSuccess\e[0m"; }
displayError()   { echo -e "\e[0;31mError\e[0m"; }

if [ $(id -u) != "0" ]; then
	echoError "must run with root"; exit 1
fi

# 创建脚本用来测试
if [[ $1 != "--rm" ]]; then
	for (( i = 1; i < 100; i++ )); do
		if ( type test$i.sh &> /dev/null ); then
			:
		else
			# 内容缩进只可以用制表符，不可以用空格
			cat > /usr/local/bin/test$i.sh <<-"EOF"
				#!/bin/bash
				export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

				echoSuccess()    { echo -n -e "\e[0;32mSuccess: \e[0m"; echo $1; }
				echoWarning()    { echo -n -e "\e[0;33mWarning: \e[0m"; echo $1; }
				echoError()      { echo -n -e "\e[0;31mError: \e[0m"; echo $1; }
				displaySuccess() { echo -e "\e[0;32mSuccess\e[0m"; }
				displayError()   { echo -e "\e[0;31mError\e[0m"; }

				if [ $(id -u) != "0" ]; then
					echoError "must run with root"; exit 1
				fi

				#


			EOF
			
			chmod 755 /usr/local/bin/test$i.sh
			
			[ -f /root/test$i.sh ] || ln -s /usr/local/bin/test$i.sh /root/test$i.sh
			
			echoSuccess "create test$i.sh"
			
			break 1
		fi
	done
else
	if [[ $2 == "" ]]; then
		find /usr/local/bin -name "test*.sh" -type f -exec rm -rf {} \;
		find /root -name "test*.sh" -type l -exec rm -rf {} \;
		echoSuccess 'delete test*.sh'
	else
		[ -f /usr/local/bin/test$2.sh ] || exit 1
		rm -rf {/usr/local/bin/test$2.sh,/root/test$2.sh}
		echoSuccess "delete test$2.sh"
	fi
fi
