#!/bin/bash
export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

echoColor()      { echo -e "\e[1m\e[$3;$2m$1\e[0m"; }
echoLine()       { echo -n $(echoColor "$1" "$2" "$3" ); }
echoSuccess()    { echo $(echoLine "Success: " "32" "40")$(echoColor "$1" "37" "40"); }
echoWarning()    { echo $(echoLine "Warning: " "33" "40")$(echoColor "$1" "37" "40"); }
echoError()      { echo $(echoLine "Error: " "31" "40")$(echoColor "$1" "37" "40"); }
displaySuccess() { echo $(echoColor "Success" "32" "40"); }
displayError()   { echo $(echoColor "Error" "31" "40"); }

if [ $(id -u) != "0" ]; then
	echoError "must run with root"; exit 1
fi

# 创建脚本用来测试
if [[ $1 != "-r" ]]; then
	for (( i = 1; i < 100; i++ )); do
		if ( type t$i.sh &> /dev/null ); then
			:
		else
			# 内容缩进只可以用制表符，不可以用空格
			cat > /usr/local/bin/t$i.sh <<-"EOF"
				#!/bin/bash
				export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
				START=$(date "+%s")

				echoColor()      { echo -e "\e[1m\e[$3;$2m$1\e[0m"; }
				echoLine()       { echo -n $(echoColor "$1" "$2" "$3" ); }
				echoSuccess()    { echo $(echoLine "Success: " "32" "40")$(echoColor "$1" "37" "40"); }
				echoWarning()    { echo $(echoLine "Warning: " "33" "40")$(echoColor "$1" "37" "40"); }
				echoError()      { echo $(echoLine "Error: " "31" "40")$(echoColor "$1" "37" "40"); }
				displaySuccess() { echo $(echoColor "Success" "32" "40"); }
				displayError()   { echo $(echoColor "Error" "31" "40"); }

				if [ $(id -u) != "0" ]; then
					echoError "must run with root"; exit 1
				fi

				if [ -s /usr/local/bin/myfunction.sh ]; then
					. /usr/local/bin/myfunction.sh
				else
					echoError "myfunction.sh not found"; exit 1
				fi

				#


			EOF
			
			chmod 755 /usr/local/bin/t$i.sh
			
			[ -f /root/t$i.sh ] || ln -s /usr/local/bin/t$i.sh /root/t$i.sh
			
			echoSuccess "create t$i.sh"
			
			break 1
		fi
	done
else
	if [[ $2 == "" ]]; then
		find /usr/local/bin -name "t[0-9]*.sh" -type f -exec rm -rf {} \;
		find /root -name "t[0-9]*.sh" -type l -exec rm -rf {} \;
		echoSuccess "remove all scripts"
	else
		for Option in $(echo "$*" | sed "s/$1//g"); do
			if [ -f /usr/local/bin/t$Option.sh ]; then
				rm -rf {/usr/local/bin/t$Option.sh,/root/t$Option.sh}
				echoSuccess "remove t$Option.sh"
			else
				echoWarning "t$Option.sh not found"
			fi
		done
	fi
fi
