#!/bin/bash
export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

echoColor()      { echo -e "\e[1m\e[$3;$2m$1\e[0m"; }
echoLine()       { echo -n $(echoColor "$1" "$2" "$3" ); }
echoSuccess()    { echo $(echoLine "Success: " "32" "40")$(echoColor "$1" "37" "40"); }
echoWarning()    { echo $(echoLine "Warning: " "33" "40")$(echoColor "$1" "37" "40"); }
echoError()      { echo $(echoLine "Error: " "31" "40")$(echoColor "$1" "37" "40"); }
displaySuccess() { echo $(echoColor "Success" "32" "40"); }
displayError()   { echo $(echoColor "Error" "31" "40"); }

if [ $(id -u) != "0" ]; then
    echoError "must run with root"; exit 1
fi

# 字颜色：30 黑 31 红 32 绿 33 黄 34 蓝 35 紫 36 天蓝 37 白
# 字背景：40 黑 41 红 42 绿 43 黄 44 蓝 45 紫 46 天蓝 47 白

# 计时器
Start=$1
Variable=$2
Front=$3
Back=$4

if [[ $Start == "" ]]; then
    echoError "mytime missing operand"
    exit 1
fi

[[ $Variable == "" ]] && Variable=34
[[ $Front == "" ]] && Front=34
[[ $Back == "" ]] && Back=40

End=$(date "+%s")
Minutes=$(( (End - Start) / 60 ))
Seconds=$(( (End - Start) % 60 ))

echo $(echoLine "$Minutes" "$Variable" "$Back")$(echoLine " minutes " "$Front" "$Back")\
$(echoLine "$Seconds" "$Variable" "$Back")$(echoColor " seconds" "$Front" "$Back")
