#!/bin/bash

export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

set -eu
#set -x

echo_color()
{
        echo -e "\e[1m\e[40;$2m$1\e[0m"
}

echo_error()
{
        echo_color "$1" "31"
        exit 1
}

echo_warning()
{
        echo_color "$1" "33"
        sleep 5
}

if [[ "$(id -u)" != "0" ]]; then
        echo_error "Error: must run with root"
fi

if [[ -s "/usr/local/bin/myfunction.sh" ]]; then
        . /usr/local/bin/myfunction.sh
else
        echo_error "Error: myfunction.sh not found"
fi

# 倒计时
export PATH=$PATH:/root/bin
clear
countdown "13" " "

# 开始安装
config-centos

install-lnmp

# 备份 LNMP
if [[ ! -s "/root/.selinux.status" ]] || ( ! grep "enabled" /root/.selinux.status &> /dev/null ); then
        backup-policy init
fi

install-nodejs

install-laravel

config-laravel

nodejs-package

composer-package

# 备份 Laravel
if [[ ! -s "/root/.selinux.status" ]] || ( ! grep "enabled" /root/.selinux.status &> /dev/null ); then
        backup-policy init
else
        echo ""
        echo_color "run command:  (1) reboot" "35"
        echo_color "              (2) backup-policy init" "35"
        echo ""
        
        rm -rf /root/.selinux.status
fi

# 锁定安装
echo "ONEKEY_LOCK=0" > /root/.quenong.lock

# 定时重启
shutdown -r +600

# 结束
time_success

curl -sS http://git.oschina.net/quefei/mycommand/raw/master/uninstall_part.sh | bash
